### train
device: 0 # -1 for using cpu, 0 for single gpu, [0,1,2,3] for multiple gpus
num_epochs: 25
batch_size: 8192
learning_rate: 0.01
load_pretrained_model: False
model_type: MLR
use_language_model_encoder: False
language_model_encoder_name: vinai/bertweet-base
# weight
downvote_weight: 3.5
user_normalization: null # null for no normalization, equal for assigning user weight = 1/votes,
# data processing
save_and_load_prepared_data: True
sample_data_ratio: 1
prepared_data_path: data/reddit/prepared_data.pt
train_at_least_n_votes: 5
submission_text_dict_path: data/reddit/submission_text_dict.pt


### curation modeling
upvote_downvote_ratio_thres: 0.9
single_user_as_cluster: False
user_clustering_method: "neural" # or "votes"
active_user_votes_thres: 5
cluster_user_num_lower_thres: 5
cluster_user_num_upper_thres: 500
preferred_submissions_venn_figure_dir: output/figures/preferred_subs