device: 0 # -1 for using cpu, 0 for single gpu, [0,1,2,3] for multiple gpus
save_and_load_prepared_data: True
prepared_data_path: data/reddit/prepared_data.pt
num_epochs: 25
batch_size: 8192
learning_rate: 0.01
unit_test: False
load_pretrained_model: False
model_type: MLR