prepared_data_path: data/reddit/a_few_users.pt
sample_method: ['USERNAME'] # , "add_weak_downvote"
model_type: Transformer # Transformer
encoder_hidden_dim: 256
language_model_encoder_name: prajjwal1/bert-mini
sample_ratio: 0.005
train_at_least_n_votes: 0
l2_normalization: 0.01

train_test_different_submissions: False
learning_rate: 0.001
num_epochs: 20
downvote_weight: 6
user_normalization: equal

batch_size: 52
sample_part_voted_users: False
use_voted_users_feature: False
add_target_user_ratio: 0.3
device: [0,1,2,3]