sample_ratio: 0.05
model_type: DCN
prepared_data_path: data/reddit/prepared_med_ID_data.pt
downvote_weight: 1
# batch_size: 64
# num_epochs: 5
num_epochs: 25
learning_rate: 0.0001
use_language_model_encoder: False
use_voted_users_feature: False
user_normalization: null # equal