sample_ratio: 0.01
model_type: DCN
sample_method: ["most_votes"]
prepared_data_path: data/reddit/prepared_med_ID_sim_new_votes_finetune.pt
downvote_weight: 20
learning_rate: 0.0001
batch_size: 1024
num_epochs: 5
use_language_model_encoder: False
sample_part_voted_users: False
use_voted_users_feature: False
user_normalization: equal
train_test_different_submissions: True
add_target_user_ratio: 0.3
