sample_user_ratio: 0.2
model_type: DCN
prepared_data_path: data/reddit/prepared_small_data.pt
user_normalization: null # equal
downvote_weight: 6
single_user_as_cluster: True
learning_rate: 0.0005
num_epochs: 10
