sample_ratio: 0.05
model_type: DCN
prepared_data_path: data/reddit/prepared_med_ID_data.pt
downvote_weight: 1.35
batch_size: 64
num_epochs: 5
use_language_model_encoder: False
use_voted_users_feature: True
sample_part_voted_users: True
user_normalization: null # equal