sample_ratio: 0.005
model_type: DCN
prepared_data_path: data/reddit/prepared_small_ID_data.pt
downvote_weight: 1.35
batch_size: 64
user_grouping_method: single_user_as_group
num_epochs: 10
use_language_model_encoder: False
sample_part_voted_users: True
use_voted_users_feature: True
user_normalization: equal