sample_data_ratio: 0.01
model_type: DCN
prepared_data_path: data/reddit/prepared_small_text_data.pt
user_normalization: null # equal
downvote_weight: 6.5
batch_size: 4
single_user_as_cluster: True
num_epochs: 5
use_language_model_encoder: True
language_model_encoder_name: roberta-base
train_at_least_n_votes: 1