unit_test: True
model_type: MLR
prepared_data_path: data/reddit/prepared_small_data.pt
user_normalization: equal # equal
downvote_weight: 6.5
# user_clustering_method: "votes"
single_user_as_cluster: True
num_epochs: 5
