sample_ratio: 0.05
model_type: DCN
prepared_data_path: data/reddit/prepared_med_ID_sim_new_votes_finetune.pt
downvote_weight: 1.35
batch_size: 64
num_epochs: 5
use_language_model_encoder: False
use_voted_users_feature: False
user_normalization: equal
train_test_different_submissions: True