sample_method: ["SUBMISSION_ID", "correlated_user_pairs"]
sample_ratio: 0.01
model_type: DCN
prepared_data_path: data/reddit/prepared_correlated_users_finetune.pt
downvote_weight: 5
num_epochs: 25
use_language_model_encoder: False
use_voted_users_feature: False
user_normalization: equal
train_test_different_submissions: True