sample_ratio: 0.01
model_type: DCN
prepared_data_path: data/reddit/prepared_med_submission_data.pt
downvote_weight: 1
batch_size: 64
user_grouping_method: single_user_as_group
num_epochs: 5
use_language_model_encoder: False
sample_method: "SUBMISSION_ID"