sample_ratio: 1
model_type: DCN
prepared_data_path: data/reddit/prepared_full_text_data.pt
downvote_weight: 0.68
batch_size: 48
user_grouping_method: single_user_as_group
num_epochs: 5
use_language_model_encoder: True
language_model_encoder_name: google/electra-small-discriminator
encoder_hidden_dim: 256