sample_method: ["SUBMISSION_ID"]
prepared_data_path: data/reddit/old.pt
model_type: DCN
sample_ratio: 0.03
sparse_features_embed_dims: {'USERNAME':64, 'SUBMISSION_ID':32, 'SUBREDDIT':8, 'AUTHOR':8, 'NSFW':4}
dense_features: ['CREATED_TIME', '#_COMMENTS']
use_voted_users_feature: False
train_at_least_n_votes: 0
train_test_different_submissions: False
learning_rate: 0.0001
num_epochs: 20
downvote_weight: 7.3