sample_user_ratio: 0.002
model_type: DCN
prepared_data_path: data/reddit/prepared_small_text_data.pt
user_normalization: null # equal
downvote_weight: 1.7
batch_size: 48
single_user_as_cluster: True
num_epochs: 5
use_language_model_encoder: True
language_model_encoder_name: google/electra-small-discriminator
encoder_hidden_dim: 256
learning_rate: 0.0001 
