posts_data_path: data/Curio/post_info.txt
votes_data_path: data/Curio/all_votes.txt
sample_ratio: 1
sample_method: 'USERNAME'
testset_proportion: 0.01
model_type: Transformer
encoder_hidden_dim: 256
language_model_encoder_name: prajjwal1/bert-mini
train_at_least_n_votes: 0
l2_normalization: 0.0001
prepared_data_path: data/Curio/finetune_CURIO_full_data.pt
train_test_different_submissions: False
learning_rate: 0.00003
load_pretrained_model: True
num_epochs: 20
downvote_weight: 2.5
user_normalization: equal_upvote_downvote # equal upvote weight and downvote weight for each user!
minority_vote_normalization: True
upvote_confidence_thres: 0.5
upvote_ratio_thres: 0.5
batch_size: 1024
sample_part_voted_users: False
use_voted_users_feature: False
add_target_user_ratio: 0
active_user_votes_thres: 0
device: [2]
submission_source: "test_data" # "test_data" or "custom"

# cp trained_models/finetune_CURIO_full_data/best.pt trained_models/deploy_CURIO_full_data/best.pt