prepared_data_path: data/reddit/med.pt
sample_method: ['SUBMISSION_ID', "equal_up_down_votes"]
model_type: Transformer
encoder_hidden_dim: 256
language_model_encoder_name: google/electra-small-discriminator
sample_ratio: 0.2
train_at_least_n_votes: 0

train_test_different_submissions: False
learning_rate: 0.0001
num_epochs: 20
downvote_weight: 20
user_normalization: equal

batch_size: 40
sample_part_voted_users: True
use_voted_users_feature: True
add_target_user_ratio: 0.3