sample_method: ['most_votes'] # , "add_weak_downvote"
model_type: Transformer
encoder_hidden_dim: 256
language_model_encoder_name: prajjwal1/bert-mini
sample_ratio: 0.005
train_at_least_n_votes: 0
l2_normalization: 0.0001
prepared_data_path: data/reddit/small_most_votes_test_diff.pt
train_test_different_submissions: True
learning_rate: 0.0001
# load_pretrained_model: True
num_epochs: 15
downvote_weight: 15
user_normalization: equal_total

batch_size: 384
sample_part_voted_users: True
use_voted_users_feature: True
add_target_user_ratio: 0.3
device: [1,2,3]