sample_method: ["selected_subreddits"]
selected_subreddits: ["r/politics", "r/Conservative", "r/Liberal", "r/Republican", "r/democrats", "r/VoteBlue", "r/Jokes", "r/science", "r/ScienceFacts", "r/technology", "r/shittyaskscience", "r/Feminism", "r/MensRights", "r/lesbian", "r/LesbianActually", "r/gay", "r/trans", "r/teenagers", "r/Showerthoughts"]
model_type: Transformer
encoder_hidden_dim: 256
language_model_encoder_name: prajjwal1/bert-mini
sample_ratio: 0.05
train_at_least_n_votes: 0
l2_normalization: 0.0001
prepared_data_path: data/reddit/subreddit_minority_no_peer_new.pt
train_test_different_submissions: False
learning_rate: 0.00003
# load_pretrained_model: True
num_epochs: 10
downvote_weight: 1.5
user_normalization: equal_upvote_downvote # equal upvote weight and downvote weight for each user!
minority_vote_normalization: True

batch_size: 64
sample_part_voted_users: False
use_voted_users_feature: False
add_target_user_ratio: 0
device: [2]
submission_source: "test_data" # "test_data" or "custom"