sample_method: ["SUBMISSION_ID"] # , "equal_up_down_votes"
prepared_data_path: data/reddit/tmp.pt
model_type: Linear
sample_ratio: 0.01
train_at_least_n_votes: 0

train_test_different_submissions: True
learning_rate: 0.0001
num_epochs: 10
downvote_weight: 1.5
user_normalization: equal

batch_size: 1024
sample_part_voted_users: False
use_voted_users_feature: False
add_target_user_ratio: 0.3

sparse_features_embed_dims: {'SUBMISSION_ID': 128, 'USERNAME': 128, 'SUBREDDIT': 128, 'AUTHOR': 128, 'NSFW': 128}
dense_features: []