prepared_data_path: data/reddit/tmp.pt
sample_method: ['SUBMISSION_ID']
model_type: Transformer
encoder_hidden_dim: 256
language_model_encoder_name: google/electra-small-discriminator
sample_ratio: 0.003
train_at_least_n_votes: 0

train_test_different_submissions: False
learning_rate: 0.0001
num_epochs: 2
downvote_weight: 7
user_normalization: equal

batch_size: 48
sample_part_voted_users: True
use_voted_users_feature: True
add_target_user_ratio: 0.3