prepared_data_path: data/reddit/tmp.pt
model_type: Transformer
sample_ratio: 0.01
train_at_least_n_votes: 0

train_test_different_submissions: False
learning_rate: 0.0001
num_epochs: 10
downvote_weight: 20
user_normalization: equal

batch_size: 1024
sample_part_voted_users: True
use_voted_users_feature: True
add_target_user_ratio: 0.3